name: Request Unity Activation File
on: workflow_dispatch # This allows you to trigger it manually
jobs:
  request-manual-activation-file:
    name: Request Manual Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Request ALF
        id: getManualALF
        uses: game-ci/unity-request-activation-file@v2
      
      - name: Upload ALF
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v20XX.X.XXXX.alf
          path: ${{ steps.getManualALF.outputs.filePath }}